#!/usr/bin/env bash

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

php /app/artisan app:init

# chown -R www:www /app/storage

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
